### ISSUE TITLE
ebookjapan.dpr missing

### ISSUE THREAD

**Issue by biggreen34** [andreili/EBookJapan#1]
Hello,
I'm trying to open the project, but ebookjapan.dpr is missing. Can you upload the file or show me how to create one?
And the tool can decrypt the image to jpg or it's "HVQ5"?

Thanks.

**Comment by andreili** [comment]
I add tonight.
The format images - did not find examples of working with them publicly available.
And yet - at the moment is not complete authentication on a server, because of what can not work directly with the server and you have to download files from the server itself.
If you do not understand what files are needed - write, add in the readme.

**Comment by Tomadz** [comment]
@andreili where is  the ebookjapan.dpr file?

**Comment by andreili** [comment]
This project is a outdated.
On now, i'm writed a new project (baset on Qt5), hosted on bitbucket. If you need him, please, puth your e-mail on bitbucket into this issue.

**Comment by Tomadz** [comment]
@andreili my bitbucket email is: tomadz96 @ gmail . com (without spaces)

**Comment by rXp** [comment]
@andreili Where is the new repository ? I would love to have access to the updated project ! 
Thanks !

**Comment by andreili** [comment]
https://bitbucket.org/andreil/books-grabber/

**Comment by rXp** [comment]
@andreili it's a private repository that is why I cannot find it. How can get access to it?

**Comment by chocolatkey** [comment]
@andreili I am also interested in this repository. I have reverse-engineered everything on EBJ up to the HVQ5 image format, which I am still struggling to translate from the assembly/pseudocode (because it is an entire image codec). How far have you gotten? (e-mail chocolatkey@gmail.com)

**Comment by andreili** [comment]
Sory, i'm very slowly :(
Pls, write direct to my mail: andreil499@gmail.com - you send me e-mail, i'm give access to a repo ;)
